### ISSUE TITLE
possibly not including SdFat?

### ISSUE THREAD

**Issue by ladyada** [earlephilhower/arduino-pico#416] opened 2022-01-14 04:53 UTC
hiya, this board package includes SdFat in its 'core' library set - which means we can't use our fork for projects with the pico because arduino will always choose the built-in version. for some libraries like Wire, EEPROM or SD, this makes sense since they're core hardware interfaces. for SdFat, it's usually considered an optional library. could we remove it from the pre-installed list and have folks install SdFat thru the library manager? 

if not ill just tell folks to manually delete SdFat from the Pico's library folder (which isnt a huge deal) but thought its worth asking! if you have stuff you want changed to SdFat we could also add it to the adafruit fork since the upstream maintainer has frozen development

**Comment by hathach** [comment] 2022-01-14 12:09
@ladyada  I have tried this locally and the reason that arduino build system prefer the bundled lib instead of the one installed via library manager is our SdFat fork `architecture=*` while the bundled lib explicitly tell rp2040. I have update our SdFat fork to explicitly list rp2040 in the architecture (along with samd,nrf52,esp32) and this help build system to select our lib in https://github.com/adafruit/SdFat/pull/12 and released as 1.5.0 . This issue could be closed now, I guess. 

https://arduino.github.io/arduino-cli/0.20/sketch-build-process/#dependency-resolution

```
If multiple libraries contain a file that matches the #include directive, the priority is determined by applying the following rules, one by one in this order, until a rule determines a winner:

A library that is architecture compatible wins against a library that is not architecture compatible (see Architecture Matching)
A library with both library name and folder name matching the include wins
A library that has better "library name priority" or "folder name priority" wins (see Library Name Priority and Folder Name Priority)
A library that is architecture optimized wins against a library that is not architecture optimized (see Architecture Matching)
A library that has a better "location priority" wins (see Location Priority)
A library that has a folder name with a better score using the "closest-match" algorithm wins
A library that has a folder name that comes first in alphanumeric order wins
```

**Comment by ladyada** [comment] 2022-01-14 15:45
thank you! its resolved :)

**Comment by earlephilhower** [comment] 2022-01-17 20:17
It's really not possible to pull out this SDFat branch from the core and use upstream, unfortunately.  Because we have our own `File` class and `File::availableForWrite` and do host-based testing as part of CI, there are about 4-5 changes that need to be there (plus a small bugfix that's not been merged upstream).  The other things like making the examples compile and run are not so big of a deal:

[diffs] https://github.com/greiman/SdFat/compare/master...earlephilhower:3a6b688b1b5112d149295813660ef9b2b7cc0ee5

Also, I think the Adafruit fork is still on the 1.x branch where this one is from ~head on the 2.x branch w/exfat and utf support (along w/a reasonably large refactoring).

FWIW, the library identifies itself as `ESP8266SDFat` in the `library.properties` file.  Is that name ignored, then?

**Comment by earlephilhower** [comment] 2022-01-17 22:11
I just realized I haven't implemented host tests, so the `#ifdef HOST_MOCK` stuff is also superfluous.  Unfortunately the 1.x vs. 2.x thing isn't. :(

**Comment by hathach** [comment] 2022-01-19 11:54
yeah, our fork have some modification as well to enable FAT12 support (FAT12_SUPPORT) as well as `ENABLE_EXTENDED_TRANSFER_CLASS` which is required to support small flash from dozens KB (internal flash) to MB (SPI Flash). Along with a few fix for FAT12 bugs as well. At the time we made our fork, the SdFat is heavily focused on development of V2 which is not ready for production while PR to V1 is not recommended.

> FWIW, the library identifies itself as ESP8266SDFat in the library.properties file. Is that name ignored, then?

Yes, It is ignored. The builder will only use the folder name for matching candidates. I guess the lib name is mostly for lib manager to index/search and install, if installed from lib manager, your lib folder will be installed to `Arduino/libraries/ESP8266SDFat`. However since your is bundled as SdFat, its naming win against `SdFat_-_Adafruit_Fork`.  

Maybe it is time for us to migrate/update to the V2 in the near future, and push the changes upstream if possible. Thank you for explaining your fork changes.

**Comment by earlephilhower** [comment] 2022-01-19 17:06
There might be another way.  Right now nobody using this core should be using SdFAT directly (in theory, anyway, since there's the `SDFS` which wraps it).  So, if I were to rename the library headers would that take care of things?  From `sdfat.h` to `esp8266sdfat.h`, for example.  It's a 1- or 2-line change in the SDFS wrapper code for me.

However, all the lower-level includes would stay the same (SdFatConfig.h, etc.)  Would there be some conflict w/your version if two headers with the same name existed in different libs?  FWIW if they're using Adafruit SdFat, they're not going to be using SDFS, so I *think* the arduino-cli will not even add esp8266sdfat to the -I path...

**Comment by earlephilhower** [comment] 2022-01-24 16:55
@hathach any suggestions?  Like I mentioned, I could rename the library directory to `ESP8266SDFat`, rename the `SDFat.h` file to `ESP8266SdFat.h`, or both very simply.  Would any of those three get your fork working properly?

**Comment by hathach** [comment] 2022-01-24 18:05
> @hathach any suggestions? Like I mentioned, I could rename the library directory to `ESP8266SDFat`, rename the `SDFat.h` file to `ESP8266SdFat.h`, or both very simply. Would any of those three get your fork working properly?

Sorry for late response, I was on a trip last 4 days and is catching up with PRs/Issues. 

`I could rename the library directory to ESP8266SDFat` :point_left: will work for us and I think is the simplest and best way **(no need to rename the SdFat.h at all)**. Any code using your ESP8266SDFat/Sdfat will continue to work as it is without additional changes. And since `SdFat - Adafruit Fork` > `ESP8266SDFat` in arduino name matching, to use Adafruit existing libs such as Floppy/Logger/Image Reader etc... user would install our fork and it will be picked up by arduino builder. I just manually rename and do the quick check.

```
Multiple libraries were found for "SdFat.h"
 Used: /home/hathach/Arduino/libraries/SdFat_-_Adafruit_Fork
 Not used: /home/hathach/Arduino/hardware/rp2040/rp2040/libraries/ESP8266SDFat
```

Thank you very much in advance for willing to help us to resolve this issue.

PS: Eventually, Adafruit will migrate to v2 and possibly pr to upstream. However, there are a few dozens of library using the current v1 already. It will take a bit of time and effort to migrate them.

**Closed** 2022-01-24 20:38 UTC

**Comment by hathach** [comment] 2022-01-25 04:26
thank you very much :+1: :+1:

**Comment by XZCE** [comment] 2024-05-07 08:45
> It's really not possible to pull out this SDFat branch from the core and use upstream, unfortunately. Because we have our own `File` class and `File::availableForWrite` and do host-based testing as part of CI, there are about 4-5 changes that need to be there (plus a small bugfix that's not been merged upstream). The other things like making the examples compile and run are not so big of a deal:
> 
> [diffs] [greiman/SdFat@master...earlephilhower:3a6b688b1b5112d149295813660ef9b2b7cc0ee5](https://github.com/greiman/SdFat/compare/master...earlephilhower:3a6b688b1b5112d149295813660ef9b2b7cc0ee5)
> 
> Also, I think the Adafruit fork is still on the 1.x branch where this one is from ~head on the 2.x branch w/exfat and utf support (along w/a reasonably large refactoring).
> 
> FWIW, the library identifies itself as `ESP8266SDFat` in the `library.properties` file. Is that name ignored, then?

A question on exFat, which this closed issue is the only one that mentions it in this repo...  How do you enable it?  It seems to me SDFS/ESP8266SDFat (I'm using SDFS on advice) is configured for Fat16/Fat32 (option 1) but changing that to Fat16/Fat32/exFat (option 3) throws errors on building my sketch.  Like error: conversion from FsFile to File32 in SDFS.cpp?

**Comment by XZCE** [comment] 2024-05-20 14:35
Clowns to the left of me, jokers to the right.  The latest source code linked here works far worse together now (than the 12 months old stuff, that I was using which did work).

:) I can't even bother to explain, USB MSD * was working before with SDFat, but not anymore.  And the issue is closed (and all) so..  Meh.
