### ISSUE TITLE
Version 3.2.1 auto upload from Arduino IDE is broken

### ISSUE THREAD

**Issue by dlkeng** [earlephilhower/arduino-pico#1486] opened 2023-05-29 15:31 UTC
After upgrading Arduino-Pico from version 3.2.0 to version **3.2.1** to get a fix for the problem of unreliable Serial.print's on Core 1 with FreeRTOS enabled on the Raspberry Pi Pico / Pico W, I am no longer able to auto upload code to the Pico from the Arduino IDE. The BOOTSEL button ***must*** always be pressed when powering on or resetting the Pico.

It appears the 1200 baud mechanism on the COM port to invoke the RPI-RP2 file system no longer works with version 3.2.1 as it did with the earlier versions. Opening the COM port now (with version 3.2.1) just appears to stop code on the Pico from running, causing its COM port to disappear in Device Manager, but no file system RPI-RP2 drive appears in File Manager. This was manually confirmed by opening the Arduino IDE Serial Monitor at 1200 baud.

This has been confirmed by going back to version 3.2.0 in which it again is working as expected.

This is compiled on a Windows 10 Pro PC with version 1.8.13 of the Arduino IDE and using V3.2.1 of Arduino-Pico. The board settings are shown in the attached image below.

![PicoW_Board](https://github.com/earlephilhower/arduino-pico/assets/2680128/1adbd460-b844-484e-82d1-b4570f17e075)

**Comment by earlephilhower** [comment] 2023-05-29 15:47
Does the upload work with the non-FreeRTOS `blink` and the `Multicore-FreeRTOS` example w/o BOOTSEL?  Trying to pinpoint if this is a FreeRTOS only thing.  FWIW it's been a week and you're the only one to report this, so I think it might be related to some specific app code interacting with the core.

**Comment by dlkeng** [comment] 2023-05-29 16:03
Good catch!

Yes, the problem only occurs when ```include "FreeRTOS.h"``` is involved. The non-FreeRTOS ```blink``` and the ```Multicore-FreeRTOS``` examples both work correctly as does my test code I was using when I removed the  ```include "FreeRTOS.h"```.

**Comment by earlephilhower** [comment] 2023-05-31 17:21
I haven't really been able to look into it, but I was able to reproduce some weirdness like you suggested.  Will try to dig into it over the week.  Thanks for checking at 3.2.0 and confirming it works, so that helps narrow down the search.

#1481 may also have an effect here, so I may need to merge that (a partial upgrade to the FreeRTOS mutex core shims, completed by #1484) and see if it's still a problem.

**Comment by pierrotm777** [comment] 2023-06-02 06:59
Hello, v3.2.1 return me an error when i try to update from 3.2.0.
![err](https://github.com/earlephilhower/arduino-pico/assets/8189970/d7dbf73f-ba22-4caa-9536-d1996f0e1313)

**Comment by dlkeng** [comment] 2023-06-02 13:05
Hi, This is not related to this issue and should probably be made into a new issue.

I also have seen this problem on every update I have attempted to make since the first version (2.7.1) of Arduino-Pico I installed. It appears that during the update process somehow Python3 crashes, holding a lock onto some of the .pyd files in the rp2040/tools/pqt-python3 folder. When this happens, Python3 is no longer shown in Windows Task Manager and cannot be "End Task" from there - I usually have to reboot to kill Python3 to release the lock on those files. And then I usually have to manually delete  "rp2040" folder in \Users\<username>\AppData\Local\Arduino15\packages as the update attempt usually fails due to the residue remaining from the original update process.

It has been enough of a problem for me that I have changed the way that I upgrade (or downgrade if need be) Arduino-Pico to the following steps:

1. exit Arduino IDE
2. verify Python is no longer running in Task Manager->Users (however, when Python hangs, it is not shown in Task Manager!)
3. delete "rp2040" folder in \Users\<username>\AppData\Local\Arduino15\packages
4. start Arduino IDE-Tools->Board:->Boards Manager...
5. search for "pico"
6. in "Raspberry Pi Pico/RP2040", select the desired version and "Install"
7. after install complete, close Boards Manager and exit and restart Arduino IDE

This is the process that is the least disruptive for me.

**Comment by pierrotm777** [comment] 2023-06-04 08:18
It's now solved :-)

Thanks for your help,

Pierre

**Comment by earlephilhower** [comment] 2023-06-04 19:44
I started looking at this today, @dlkeng .  However, I am unable to reproduce any failures w/any of the examples

My earlier `Serial` weirdness in https://github.com/earlephilhower/arduino-pico/issues/1486#issuecomment-1570619415 was because I had `minicom` still running in another (hidden) terminal and it was grabbing the `/dev/ttyACMx` instead of the IDE serial monitor.  I actually was having trouble with bare-metal apps, too, because of this.  Closing that `minicom` returned everything to normal.  D'oh.

I even tried doing a very heavy dual-core, 3-task`Serial` workload and was still able to upload fine.

Can you please provide a small MCVE sketch that reproduces the failure?  OTW I really can't debug here...

**Comment by earlephilhower** [comment] 2023-06-04 20:20
Okay, coffee :coffee: has now finally kicked in.

I've cleaned up my core directories from any cruft and (a) I was able to reproduce your failure, @dlkeng  and (b) the trivial fix is in #1495.   I was able to see the hang w/o this fix, and to reboot successfully w/it.  So, once committed in a few mins please pull the `git ` head and try your code once again (`head` also includes a CoreMutex fix which really helps w/multicore Serial output!).

**Closed** 2023-06-04 20:28 UTC
Labels: bug, freertos

**Comment by dlkeng** [comment] 2023-06-05 02:22
I can confirm this issue has now been resolved.
