### ISSUE TITLE
UnicodeDecodeError in tools/uf2conv.py on Win10

### ISSUE THREAD

**Issue by 759401524** [earlephilhower/arduino-pico#116] opened 2021-04-28 03:14 UTC
Win10，arduino-ide 2.0.0

```
Sketch uses 241448 bytes (11%) of program storage space. Maximum is 2093056 bytes.
Global variables use 16916 bytes (6%) of dynamic memory, leaving 245228 bytes for local variables. Maximum is 262144 bytes.

--------------------------
Compilation complete.
Resetting COM4
Converting to uf2, output size: 496640, start address: 0x2000
Traceback (most recent call last):
  File "C:\Users\Mulong\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\1.1.0/tools/uf2conv.py", line 368, in <module>
    main()
  File "C:\Users\Mulong\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\1.1.0/tools/uf2conv.py", line 355, in main
    drives = get_drives()
  File "C:\Users\Mulong\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\1.1.0/tools/uf2conv.py", line 233, in get_drives
    for line in to_str(r).split('\n'):
  File "C:\Users\Mulong\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\1.1.0/tools/uf2conv.py", line 225, in to_str
    return b.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 129: invalid continuation byte
Upload error: Error: 2 UNKNOWN: uploading error: uploading error: exit status 1

```

**Comment by earlephilhower** [comment] 2021-04-29 23:25
Duplicate of #95

**Closed by earlephilhower** 2021-04-29 23:25 UTC
